- name: Configure color prompt
  replace:
    dest: /home/vagrant/.bashrc
    regexp: '#force_color_prompt=yes'
    replace: force_color_prompt=yes

- name: Configure Zabbix Sender
  block:
    - name: Configure Server cron
      cron:
        name: Zabbix Sender Server cron
        user: zabbix
        job: PATH=$PATH:/usr/local/bin /vagrant/zabbix-redis.py -i '6379, 6380, 6381, 7000, 7001, 7002, 7003, 7004, 7005' -t server send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1

    - name: Configure Sentinel cron
      cron:
        name: Zabbix Sender Sentinel cron
        user: zabbix
        job: PATH=$PATH:/usr/local/bin /vagrant/zabbix-redis.py -i '26379, 26380, 26381' -t sentinel send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1
